### ISSUE TITLE
Broken: `(WL @(a b c d))`

### ISSUE THREAD

**Issue by holyjak** [scicloj/wolframite#21]
See https://github.com/scicloj/wolframite/pull/14#discussion_r1403363309

Note: From the code of the `convert` fn it seems that we are converting such expression "from prefix form"  (the opposite of `meta` 🤷 which converts "from postfix form"). So `@(a b c)` becomes `a[b[c]]` and `'(clojure.core/meta (a b c))` becomes `c[b[a]]`.

As commented below,

> Coming from clojure-land, it just seems like unnecessary extra syntax.

so may be not worth fixing.

**Comment by holyjak** [comment]
Closing, no idea what that code was supposed to do.

**Comment by qazwsxpawel** [comment]
I think @ in WL is some kind of function composition or application
operator, but I’m not sure

*---------------------*
*Pawel Ceranka*
*Nette: Research OS for the Web*
https://www.nette.io/
London, UK

**Comment by holyjak** [comment]
@light-matters do you have some insight into this, pls?

**Comment by light-matters** [comment]
Usually functions are called using "f[x]" notation but it's possible to call them using "f@x". The main use of this is for function composition (https://reference.wolfram.com/language/ref/Composition.html), so I'm guessing that the intention was to replace a@b@c@d . 

Crazily, I used to use it simply because mathematica didn't have an easy way of inserting brackets!

Coming from clojure-land, it just seems like unnecessary extra syntax.

**Comment by holyjak** [comment]
Are you saying that Clojure devs can do whatever they need without `@` because they can simply do `(f (g (h ...)))`? Or could there be a case where they would need the function composition for some reason?

**Comment by holyjak** [comment]
Closing - as discussed, it may not be useful enough to be worth supporting. Will reopen if users actually need this.
