### ISSUE TITLE
Simplify writing expression with interpolation of values via quote/unquote (auto-strip sym namespaces)

### ISSUE THREAD

**Issue by holyjak** [scicloj/wolframite#30]
It is very laborious to write expression where you want some vars resolved, if you haven't run `load-all-symbols`:

```clojure
(let [x 1]
  (wl/eval `(~'Plus ~x 1)))
```

Since the backtick turns every symbol to a qualified one, we need to prefix every one with `~#` to ensure they stay simple symbols. This is annoying.

## Proposal 

Strip namespaces automatically from forms passed to eval  - but make it possible to keep selected ones. This is to support Wolfram scopes (if we ever get good support for them). Perhaps st. like `(wl/eval ... {:scopes #{:my-scope1 ..}})`?

**Comment by light-matters** [comment]
This is a note to say that un-qualify is an existing function within the library and presumably is already used somewhere. The idea of preserving certain namespaces/scopes, or 'contexts' in Wolfram terminology, would be new though and potentially useful.

**Comment by qazwsxpawel** [comment]
If I can chime in to maybe provide a bit of historical context...
(going by memory so might not be 100% accurate ;))

My thinking was that `wl/eval` (like `eval`) would be something that's 'low-level' and not really used in 90% of daily programming practice, so to speak. 
It's a building block that might be used to provide more convenient higher level constructs or to access the full, raw power of the integration ;) 

This would be coupled with a workflow that's more 'natural'—my preferred approach was loading all (or some) symbols into a namespace (say `'w`) and using that. 

Then the effect of that is a pretty clean and familiar (to the clojurist) workflow—the entire (or part of) Wolfram Language becomes a library (so `w/Plus`, `w/GeoDistance`)!
(as a side note, you can load different symbols to different namespaces e.g. all of https://reference.wolfram.com/language/guide/MachineLearning.html into `ml`, so `ml/Predict`, `ml/Classify`—which is cool, but not sure how practical it would seem to most people) 

This is all not to say that this is the right way to do it ;) 
I'm merely pointing out that the fact that it's this way is because of some concrete *design decisions* backed by a *model of desired usage pattern* and I think that's a very helpful thing to have (an iterate on!). 

Now that there are more people involved it would be good to write it down I think.
It makes some technical decisions like this one easier to make. 
E.g. if `wl/eval` is in fact a low-level construct that is not meant to be used in typical usage (that is defined by this *design document* that contains description of model usage) then it's OK and in fact desired to keep it as simple as possible even if it's a bit awkward to use. 

Not sure how much I can contribute to this but always happy to chat and share some thinking. 

I'm really happy that you are developing this library! 
Thanks you 🙏

**Comment by holyjak** [comment]
Good points, thank you for chiming in, @qazwsxpawel We've decided to pursue `load-all-symbols` as the recommended way of using Wolframite, and keeping the symbol-based one as a more primitive (and laborious) one.

Notice that we had to abandon the interned symbol being actual functions calling the kernel, because nested calls and symbols were then problematic: you couldn't do `(Plus 1 Pi)` (b/c Pi would be a `fn`, not a symbol) and doing `(Plus 1 (Plus 2 3))` would make _two_ calls to the Kernel, instead of one.
